"""
SAM2 (Segment Anything Model 2) adapter for aerial image segmentation.

This module implements the SegmentationModel interface for SAM2, providing
automatic mask generation for building segmentation in aerial images.
"""

from typing import Any, List, Dict
import numpy as np
import torch
from sam2.build_sam import build_sam2
from sam2.automatic_mask_generator import SAM2AutomaticMaskGenerator

from .segmentation_model import SegmentationModel


class SAM2Adapter(SegmentationModel):
    """
    Adapter for SAM2 (Segment Anything Model 2).
    
    This adapter uses SAM2's automatic mask generation to segment buildings
    in aerial images. SAM2 is a foundation model that can segment objects
    without specific training on the target domain.
    
    Attributes:
        checkpoint_path: Path to SAM2 model checkpoint file
        model_cfg: Model configuration name (e.g., 'sam2_hiera_l.yaml')
        predictor: SAM2 automatic mask generator instance
    """
    
    def __init__(self, checkpoint_path: str, model_cfg: str):
        """
        Initialize SAM2Adapter.
        
        Args:
            checkpoint_path: Path to SAM2 checkpoint file
            model_cfg: Model configuration name
        """
        self.checkpoint_path = checkpoint_path
        self.model_cfg = model_cfg
        self.predictor = None
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
    
    def load(self) -> None:
        """
        Load SAM2 model and initialize automatic mask generator.
        
        Raises:
            Exception: If model loading fails
        """
        try:
            # Build SAM2 model
            sam2_model = build_sam2(
                config_file=self.model_cfg,
                ckpt_path=self.checkpoint_path,
                device=self.device
            )
            
            # Create automatic mask generator
            self.predictor = SAM2AutomaticMaskGenerator(
                model=sam2_model,
                points_per_side=32,
                pred_iou_thresh=0.7,
                stability_score_thresh=0.85,
                crop_n_layers=1,
                crop_n_points_downscale_factor=2,
            )
            
        except Exception as e:
            raise Exception(f"Failed to load SAM2 model: {str(e)}")
    
    def preprocess(self, image: np.ndarray) -> np.ndarray:
        """
        Apply SAM2-specific preprocessing.
        
        SAM2 expects RGB images as numpy arrays with uint8 dtype.
        This method ensures the image is in the correct format.
        
        Args:
            image: Input image as numpy array with shape (H, W, C)
        
        Returns:
            Preprocessed image as numpy array in RGB format
        """
        # Ensure image is RGB (should already be from ImageProcessor)
        if image.shape[2] != 3:
            raise ValueError(f"Expected 3-channel RGB image, got {image.shape[2]} channels")
        
        # Ensure uint8 dtype
        if image.dtype != np.uint8:
            image = image.astype(np.uint8)
        
        return image
    
    def predict(self, preprocessed_input: np.ndarray) -> List[Dict[str, Any]]:
        """
        Run SAM2 automatic mask generation.
        
        Args:
            preprocessed_input: Preprocessed RGB image
        
        Returns:
            List of mask dictionaries from SAM2, each containing:
                - 'segmentation': binary mask as numpy array
                - 'area': mask area in pixels
                - 'bbox': bounding box [x, y, w, h]
                - 'predicted_iou': predicted IoU score
                - 'stability_score': stability score
        
        Raises:
            Exception: If prediction fails
        """
        if self.predictor is None:
            raise Exception("Model not loaded. Call load() first.")
        
        try:
            # Generate masks
            masks = self.predictor.generate(preprocessed_input)
            return masks
            
        except Exception as e:
            raise Exception(f"SAM2 prediction failed: {str(e)}")
    
    def postprocess(self, raw_output: List[Dict[str, Any]]) -> np.ndarray:
        """
        Convert SAM2 masks to binary segmentation mask.
        
        This method combines all generated masks into a single binary mask
        where any pixel covered by at least one mask is marked as building (255),
        and all other pixels are marked as background (0).
        
        Args:
            raw_output: List of mask dictionaries from SAM2
        
        Returns:
            Binary segmentation mask with shape (H, W), dtype uint8,
            and values in {0, 255}
        """
        if not raw_output:
            # No masks generated, return empty mask
            # We need to get dimensions from somewhere - this is a fallback
            raise ValueError("No masks generated by SAM2")
        
        # Get image dimensions from first mask
        first_mask = raw_output[0]['segmentation']
        height, width = first_mask.shape
        
        # Initialize combined mask
        combined_mask = np.zeros((height, width), dtype=np.uint8)
        
        # Combine all masks using logical OR
        for mask_dict in raw_output:
            mask = mask_dict['segmentation']
            combined_mask = np.logical_or(combined_mask, mask).astype(np.uint8)
        
        # Convert to binary format (0 or 255)
        combined_mask = combined_mask * 255
        
        return combined_mask
